1.

In [4]:
import  numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import xlrd
%matplotlib inline
import warnings

In [5]:
columns = ['Date','Time','CO(GT)','PT08.S1(CO)','NMHC(GT)',
           'C6H6(GT)','PT08.S2(NMHC)','NOx(GT)','PT08.S3(NOx)','NO2(GT)',
           'PT08.S4(NO2)','PT08.S5(O3)','T','RH','AH']

In [6]:
df=pd.read_excel("AirQualityUCI.xlsx")
df

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  \
0    2004-03-10  18:00:00     2.6      1360.00       150  11.881723   
1    2004-03-10  19:00:00     2.0      1292.25       112   9.397165   
2    2004-03-10  20:00:00     2.2      1402.00        88   8.997817   
3    2004-03-10  21:00:00     2.2      1375.50        80   9.228796   
4    2004-03-10  22:00:00     1.6      1272.25        51   6.518224   
...         ...       ...     ...          ...       ...        ...   
9352 2005-04-04  10:00:00     3.1      1314.25      -200  13.529605   
9353 2005-04-04  11:00:00     2.4      1162.50      -200  11.355157   
9354 2005-04-04  12:00:00     2.4      1142.00      -200  12.374538   
9355 2005-04-04  13:00:00     2.1      1002.50      -200   9.547187   
9356 2005-04-04  14:00:00     2.2      1070.75      -200  11.932060   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  \
0           1045.50    166.0       1056.25    113.0       1692.00   
1            954.75    103.0       1173.75     92.0       1558.75   
2            939.25    131.0       1140.00    114.0       1554.50   
3            948.25    172.0       1092.00    122.0       1583.75   
4            835.50    131.0       1205.00    116.0       1490.00   
...             ...      ...           ...      ...           ...   
9352        1101.25    471.7        538.50    189.8       1374.25   
9353        1027.00    353.3        603.75    179.2       1263.50   
9354        1062.50    293.0        603.25    174.7       1240.75   
9355         960.50    234.5        701.50    155.7       1041.00   
9356        1047.25    265.2        654.00    167.7       1128.50   

      PT08.S5(O3)       T         RH        AH  
0         1267.50  13.600  48.875001  0.757754  
1          972.25  13.300  47.700000  0.725487  
2         1074.00  11.900  53.975000  0.750239  
3         1203.25  11.000  60.000000  0.786713  
4         1110.00  11.150  59.575001  0.788794  
...           ...     ...        ...       ...  
9352      1728.50  21.850  29.250000  0.756824  
9353      1269.00  24.325  23.725000  0.711864  
9354      1092.00  26.900  18.350000  0.640649  
9355       769.75  28.325  13.550000  0.513866  
9356       816.00  28.500  13.125000  0.502804  

[9357 rows x 15 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
cols = list(df.columns)
train_minmax = MinMaxScaler()
df[['PT08.S1(CO)','NMHC(GT)']]=train_minmax.fit_transform(df[['PT08.S1(CO)','NMHC(GT)']])
df = pd.DataFrame(df,columns =cols)
df.head(10)

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  \
0 2004-03-10  18:00:00     2.6     0.696506  0.251980  11.881723   
1 2004-03-10  19:00:00     2.0     0.666257  0.224622   9.397165   
2 2004-03-10  20:00:00     2.2     0.715258  0.207343   8.997817   
3 2004-03-10  21:00:00     2.2     0.703427  0.201584   9.228796   
4 2004-03-10  22:00:00     1.6     0.657328  0.180706   6.518224   
5 2004-03-10  23:00:00     1.2     0.623730  0.171346   4.741012   
6 2004-03-11  00:00:00     1.2     0.618373  0.166307   3.624399   
7 2004-03-11  01:00:00     1.0     0.596607  0.166307   3.326677   
8 2004-03-11  02:00:00     0.9     0.577743  0.161267   2.339416   
9 2004-03-11  03:00:00     0.6     0.540127  0.157667   1.696658   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0        1045.50    166.0       1056.25    113.0       1692.00      1267.50   
1         954.75    103.0       1173.75     92.0       1558.75       972.25   
2         939.25    131.0       1140.00    114.0       1554.50      1074.00   
3         948.25    172.0       1092.00    122.0       1583.75      1203.25   
4         835.50    131.0       1205.00    116.0       1490.00      1110.00   
5         750.25     89.0       1336.50     96.0       1393.00       949.25   
6         689.50     62.0       1461.75     77.0       1332.75       732.50   
7         672.00     62.0       1453.25     76.0       1332.75       729.50   
8         608.50     45.0       1579.00     60.0       1276.00       619.50   
9         560.75   -200.0       1705.00   -200.0       1234.75       501.25   

        T         RH        AH  
0  13.600  48.875001  0.757754  
1  13.300  47.700000  0.725487  
2  11.900  53.975000  0.750239  
3  11.000  60.000000  0.786713  
4  11.150  59.575001  0.788794  
5  11.175  59.175000  0.784772  
6  11.325  56.775000  0.760312  
7  10.675  60.000000  0.770238  
8  10.650  59.674999  0.764819  
9  10.250  60.200001  0.751657

In [8]:
labelencoder = LabelEncoder()
df['AH']=labelencoder.fit_transform(df['AH'])
df.columns = cols
df.head(10)

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  \
0 2004-03-10  18:00:00     2.6     0.696506  0.251980  11.881723   
1 2004-03-10  19:00:00     2.0     0.666257  0.224622   9.397165   
2 2004-03-10  20:00:00     2.2     0.715258  0.207343   8.997817   
3 2004-03-10  21:00:00     2.2     0.703427  0.201584   9.228796   
4 2004-03-10  22:00:00     1.6     0.657328  0.180706   6.518224   
5 2004-03-10  23:00:00     1.2     0.623730  0.171346   4.741012   
6 2004-03-11  00:00:00     1.2     0.618373  0.166307   3.624399   
7 2004-03-11  01:00:00     1.0     0.596607  0.166307   3.326677   
8 2004-03-11  02:00:00     0.9     0.577743  0.161267   2.339416   
9 2004-03-11  03:00:00     0.6     0.540127  0.157667   1.696658   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0        1045.50    166.0       1056.25    113.0       1692.00      1267.50   
1         954.75    103.0       1173.75     92.0       1558.75       972.25   
2         939.25    131.0       1140.00    114.0       1554.50      1074.00   
3         948.25    172.0       1092.00    122.0       1583.75      1203.25   
4         835.50    131.0       1205.00    116.0       1490.00      1110.00   
5         750.25     89.0       1336.50     96.0       1393.00       949.25   
6         689.50     62.0       1461.75     77.0       1332.75       732.50   
7         672.00     62.0       1453.25     76.0       1332.75       729.50   
8         608.50     45.0       1579.00     60.0       1276.00       619.50   
9         560.75   -200.0       1705.00   -200.0       1234.75       501.25   

        T         RH    AH  
0  13.600  48.875001  2438  
1  13.300  47.700000  2176  
2  11.900  53.975000  2371  
3  11.000  60.000000  2655  
4  11.150  59.575001  2671  
5  11.175  59.175000  2638  
6  11.325  56.775000  2456  
7  10.675  60.000000  2520  
8  10.650  59.674999  2489  
9  10.250  60.200001  2385

In [9]:
cols.remove('Date')
cols.remove('Time')
print(cols)
x_train, y_train = df[cols].values, df['AH'].values
x_train,x_test,y_train,y_test=train_test_split(x_train,y_train,test_size=0.2,random_state=42)

['CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)', 'T', 'RH', 'AH']


In [10]:

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(x_train)

(7485, 13)
(7485,)
(1872, 13)
(1872,)
[[ 3.40000000e+00  0.00000000e+00  0.00000000e+00 ... -2.00000000e+02
  -2.00000000e+02  0.00000000e+00]
 [ 1.20000000e+00  5.19589240e-01  1.92944564e-01 ...  1.05750000e+01
   5.77250004e+01  2.24100000e+03]
 [ 1.20000000e+00  4.93247014e-01  0.00000000e+00 ...  6.77500010e+00
   4.10499992e+01  4.88000000e+02]
 ...
 [ 3.60000000e+00  7.32336198e-01  0.00000000e+00 ...  2.26249995e+01
   6.13999996e+01  8.36900000e+03]
 [ 4.00000000e+00  7.22178815e-01  5.34197264e-01 ...  1.91500001e+01
   3.56500006e+01  2.62100000e+03]
 [ 3.80000000e+00  7.28429512e-01  0.00000000e+00 ...  1.33000000e+01
   5.62000008e+01  3.17100000e+03]]


In [11]:
def mape_loss_func(labels,preds):
    mask=labels!=0
    return np.fabs((preds[mask]-labels[mask])/labels[mask]).mean()

In [12]:
def mape(y_true, y_pred):
    return np.mean(np.abs((y_pred - y_true) / y_true)) * 100

In [13]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from sklearn.ensemble import RandomForestRegressor
import sklearn.metrics as metrics
clf=RandomForestRegressor(n_estimators = 52,random_state=42)       
clf.fit(x_train,y_train)                        
predict=clf.predict(x_test)            

print("MAPE : %.4g" % mean_absolute_percentage_error(y_test, predict))
print("RMSE : %.4g" % metrics.mean_squared_error(y_test, predict,squared=False))

MAPE : 0.0007619
RMSE : 1.108


In [14]:
from sklearn import tree
from sklearn import datasets
import pydotplus

In [1]:
iris=datasets.load_iris()

NameError: ignored

In [16]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [17]:
X=iris.data
y=iris.target

In [18]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [19]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
clf=tree.DecisionTreeClassifier(criterion='entropy').fit(X,y)

In [21]:
clf.score(X,y)

1.0

In [22]:
from graphviz import Digraph
import pydotplus

dot_data=tree.export_graphviz(clf,out_file=None)
graph=pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf('iris.pdf')

True

2.

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [25]:
clf=tree.DecisionTreeClassifier(criterion='entropy').fit(X_train,y_train)

In [26]:
clf.score(X_train,y_train)

1.0

In [27]:
clf.predict(X_test)

array([1, 0, 1, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 1, 2, 2,
       2, 2, 0, 1, 1, 1, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0,
       0])

In [28]:
clf.score(X_test,y_test)

0.8888888888888888

In [29]:
clf=tree.DecisionTreeClassifier(criterion='entropy',max_depth=3).fit(X_train,y_train)

In [30]:
clf.predict(X_test)

array([1, 0, 1, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 2, 1, 1, 1,
       2, 2, 0, 1, 1, 1, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0,
       0])

In [31]:
clf.score(X_train,y_train)

0.9809523809523809

In [32]:
clf.score(X_test,y_test)

0.9555555555555556

In [33]:
clf=tree.DecisionTreeClassifier(criterion='gini',max_depth=3).fit(X_train,y_train)

In [34]:
clf.predict(X_test)

array([1, 0, 1, 2, 2, 2, 0, 0, 2, 0, 0, 0, 2, 2, 2, 1, 2, 0, 2, 1, 1, 1,
       2, 2, 0, 1, 1, 1, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0,
       0])

In [35]:
clf.score(X_test,y_test)

0.9555555555555556

In [36]:
dot_data=tree.export_graphviz(clf,out_file=None)
graph=pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf('iris_gini_max3.pdf')

True

3.KNN

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [38]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import neighbors
clf = neighbors.KNeighborsClassifier()
iris_clf = clf.fit(X_train, y_train)

In [39]:
test_y_predicted = iris_clf.predict(X_test)
print(test_y_predicted)

[2 1 2 2 2 1 2 1 2 2 1 2 0 2 1 2 1 0 0 2 0 1 2 0 2 2 1 1 2 0 0 0 0 1 2 0 2
 0 0 1 1 2 0 0 1]


In [40]:
clf.score(X_test,y_test)

0.9555555555555556

In [47]:
from sklearn.tree import export_graphviz
dot_data=tree.export_graphviz(clf,out_file=None)
graph=pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf('test2.pdf')

True

4.隨機森林

In [42]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from sklearn.ensemble import RandomForestClassifier
import sklearn.metrics as metrics
df=pd.read_excel("AirQualityUCI.xlsx")

clf=RandomForestClassifier(n_estimators = 52,random_state=42)       
clf.fit(X_train,y_train)                          
predict=clf.predict(X_test)   

In [43]:
test_y_predicted = iris_clf.predict(X_test)
print(test_y_predicted)

[2 1 2 2 2 1 2 1 2 2 1 2 0 2 1 2 1 0 0 2 0 1 2 0 2 2 1 1 2 0 0 0 0 1 2 0 2
 0 0 1 1 2 0 0 1]


In [44]:
clf.score(X_test,y_test)

0.9555555555555556

In [45]:
from sklearn.tree import export_graphviz
clf=tree.DecisionTreeClassifier(criterion='gini',max_depth=3).fit(X_train,y_train)
dot_data=tree.export_graphviz(clf,out_file=None)
graph=pydotplus.graph_from_dot_data(dot_data)
graph.write_pdf('test.pdf')

True